### ISSUE TITLE
IBM 5150 fails to start on 0.2.0b stable due to missing overlay

### ISSUE THREAD

**Issue by DragomirPazura** [dbalsom/martypc#107]
With default config switching machine in martypc.toml to ibm5150_64k makes the emulator instantly quit. Setting RUST_LOG=trace reveals following info:
Error getting machine config: Machine configuration overlay not found: pcxt_2_360k_floppies
Setting the overlay up allows the machine to start.

Quick fix is to set up missing overlay in MartyPC\configs\machines\config_overlays.toml by finding the config block for pcxt_4_360k_floppies, copying it and pasting, then deleting entries with last 2 floppies and changing the name to "pcxt_2_360k_floppies". 

Build info:
0.2.0b stable binary, downloaded from https://github.com/dbalsom/martypc/releases/tag/0.2.0b

Edit: Please also add info in issue 51 that after setting environment variable RUST_LOG=trace MartyPC needs to be started from command line as it prints debug log there.

**Comment by dbalsom** [comment]
Thanks for the report. Some of my overlay names were ... aspirational. I'm glad the system is flexible enough to easily fix!
