### ISSUE TITLE
Monochrome blinks with colors in Doomtd3

### ISSUE THREAD

**Issue by Vutshi** [dbalsom/martypc#114]
**Describe the bug**
Monochrome image blinking with yellow or red colors.

**To Reproduce**
Run [doomtd3](https://github.com/FrenkelS/doomtd3) in [16-bit DOS 640x200 2 color CGA](https://github.com/FrenkelS/doomtd3/releases/download/v20240401/DOOMTD16-v20240401.zip)

**Expected behavior**
Monochrome image

**Screenshots**
https://github.com/dbalsom/martypc/assets/4971779/93b662dc-3258-4dee-ad68-ea3626064613

**Environment (please complete the following information):**
 - macOS 13.6.6 (22G630)
 - 2,3 GHz Quad-Core Intel Core i7
 - Intel Iris Plus Graphics 

**Build info**
  - Built from source a05a41f6a1b0b735a2ae277fc8100834f3cab80e

**Comment by dbalsom** [comment]
Can you share your vhd or floppy or however you are running this

**Comment by Vutshi** [comment]
Hi @dbalsom,
here is the disk image
[COMPAQ-DOS5_doom.img.zip](https://github.com/dbalsom/martypc/files/15181328/COMPAQ-DOS5_doom.img.zip)

Best

**Comment by FrenkelS** [comment]
I'm the creator of doomtd3.
This is [intended behaviour](https://github.com/FrenkelS/doomtd3/blob/main/i_ibm.c#L67). When an item is picked up the screen turns yellow and when the player is hit the screen turns red.

In the [CGA 640x200 graphics mode](https://en.wikipedia.org/wiki/Color_Graphics_Adapter#640_%C3%97_200), the foreground color can be changed to any of the 16 CGA colors, while the background stays black.

The background color can be changed on an Amiga, so I did that in the [Amiga version](https://www.youtube.com/watch?v=OiuOtls0gX4) of doomtd3.

**Comment by dbalsom** [comment]
I had a suspicion this was the case but I haven't had time to check on real hardware. Thanks @FrenkelS .
