### ISSUE TITLE
clipboard integration of the hosted OS window on Mac OS X

### ISSUE THREAD

**Issue by darvin** [dbalsom/martypc#12]
- *cmd+c* should **copy**
 - *cmd+v* should **paste**
 - *cmd+x* should **cut**

only text in hosted MS-DOS 7.22 OS that could be selectable: for example in Turbo Pascal or Norton Commander editor/viewer (`c:\nc\nc`, `c:\tp\turbo`) could be copied. Probably needs some computer vision model or simple color based heuristics: 

## Edit:

```rust
fn getSelectedText(&self) -> String {
   // get text/colors from video memory
   // selected text is in the middle of the screen, not first or last line
   // selected text likely to have non primary or secondary background
   // selected text likely to have blinking cursor next to it (?)
}
```

#### *OCR*

```rust
fn getSelectedText(&self) -> String {
  // extracts list of colors of the screenshot of the TUI DOS program
  // ocr's screenshot of TUI DOS program - gets each letter's bounding boxes
  // calculates colors of each letter and its background
  // heuristically determines what is the selected text:
   // selected text is in the middle of the screen, not first or last line
   // selected text likely to have non primary or secondary background
   // selected text likely to have blinking cursor next to it (?)
}
```

**Comment by dbalsom** [comment]
I do not currently have clipboard integration on any platform, although it is planned.

I do not plan to support selecting text directly from the emulated display.   I will likely add a debug window that will show a text representation of video memory for the current screen where you could copy the characters from.

**Comment by darvin** [comment]
> I do not currently have clipboard integration on any platform, although it is planned.

id like to implement it - with your design if you'll share the details

> I do not plan to support selecting text directly from the emulated display.

it is supported by Turbo Pascal and by Norton Commander - their internal text selection

> I will likely add a debug window that will show a text representation of video memory for the current screen where you could copy the characters from.


oh that's great! that would allow to skip OCR altogether and just do heuristics for selection

**Comment by dbalsom** [comment]
> > I do not currently have clipboard integration on any platform, although it is planned.
> 
> id like to implement it - with your design if you'll share the details

egui has a clipboard integration feature, I just need to enable it

> it is supported by Turbo Pascal and by Norton Commander - their internal text selection

I'm sure you can select text in various dos programs, but there's no standard dos 'clipboard' so if you copy text in turbo pascal it likely gets copied to memory in a completely different location than if you copied text in Norton commander.  I would have to add a bunch of hacks for each program to access each program's clipboard, and it could even vary from version to version, just doesn't seem practical.   I think the video memory viewer is a more universally 'useful' option. I could also implement LPT to clipboard so you could copy printer output, on printscreen, for example

> oh that's great! that would allow to skip OCR altogether and just do heuristics for selection

yeah there's no real need to do OCR, in text mode , the characters are in memory, they're just turned into pixels. If you really wanted to make a text selection mode, you could, you'd just need to detect you're in text mode and calculate the right screen offsets based on CRTC registers and then you could map the mouse cursor to character cell.  I just think a special window is a bit easier to implement.

**Comment by dbalsom** [comment]
The clipboard has been enabled in branch 0.1.3

**Comment by dbalsom** [comment]
took me a while to get around to this, but there's now a text mode viewer you can copy text out of
![image](https://github.com/dbalsom/martypc/assets/7229541/7351b773-97d3-4a45-bfad-0cd2d982b140)
