### ISSUE TITLE
Digger Remastered issue

### ISSUE THREAD

**Issue by Vutshi** [dbalsom/martypc#127]
**Describe the bug**
[Digger Remastered](http://www.digger.org/index.html) seems to be stuck at switching CGA graphics mode.

**To Reproduce**
1. Boot the attached DOS 3.3 image with the game included.
2. Execute `digger /C`
3. MartyPC is stuck at the black screen

**Expected behavior**
The game runs in 86box emulator. In MartyPC (using various BIOSes) it loops indefinitely:
```
166C7 0C6B:A017 EC                       in al, dx                       
166C8 0C6B:A018 A8 08                    test al, 8h                  
166CA 0C6B:A01A 74 FB                    jz FFFDh
```
<img width="1440" alt="Screenshot 2024-06-23 at 22 13 18" src="https://github.com/dbalsom/martypc/assets/4971779/3ec3035b-748e-453c-8eb2-43300298642c">

**Environment:**
 - macOS 13.6.7 (22G720)
 - 2,3 GHz Quad-Core Intel Core i7
 - Intel Iris Plus Graphics
 - Rust 1.79.0

**Build info**
  - MartyPC 0.2.2 build from 0f818057f6a8fc8cd440c2602af43a5a650e3311

**Disk image**
[MSDOS330+digger.img.zip](https://github.com/user-attachments/files/15945895/MSDOS330%2Bdigger.img.zip)

**Comment by dbalsom** [comment]
Does this work on hardware? because those CRTC parameters are completely bonkers.

**Comment by dbalsom** [comment]
Looks like the game has detected a VGA somehow despite the /C flag, and since the register file is different we get nonsense in there.

**Comment by dbalsom** [comment]
ok, fixed.
![image](https://github.com/dbalsom/martypc/assets/7229541/1346eb0e-97e3-4990-95ed-8c9da41e54e4)

you're gonna see some weird stuff when the game starts up. I talked to reenigne and he spotted a bug - the game actually sets up VGA mode, then looks at the command line, then sets up CGA mode. 

the poor CGA card just has to deal with some crazy parameters for a brief moment.
I wasn't properly masking the maximum scanline address register, but I was properly masking the scanline address counter, so when it got the absolutely crazy value of 64, the counter would get to 31 then wrap around to 0 again. this means the CGA never thought it completed a row, and never incremented VCC.  Thus, no vsyncs, which is what the game got stuck polling for.

**Comment by Vutshi** [comment]
That was fast :)

**Comment by dbalsom** [comment]
helps that i was already sitting here working on MartyPC when the issue came in! thanks for the report.
