### ISSUE TITLE
Some PCs of the era had more than 640KB memory on board like, Zenith Z-148 that had 768KB and Zenith Z-159 that had 1.2MB. Is it possible to add a feature to increase the memory up to a certain amount? Let's say 2MB. DOS may not handle that memory but Minix and other OSes may.

### ISSUE THREAD

**Issue by starcrescent** [dbalsom/martypc#135]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dbalsom** [comment]
Please don't try to cram the entire text of your issue in the title.

The limitation of conventional memory really comes down to device conflicts. Supporting the B8000 address of the standard CGA+ text mode limits us to 736k. If this system supported 768k, then it had some sort of alternate base address for video memory. I'm not familiar enough with the system to say.

I am a bit skeptical of the Z-159 having 1.2MB of conventional memory - from what I'm reading it is based on an 8088 which can only address 1MB and that leaves you nothing for devices and ROMs.  It is possible that some of this memory was mapped into the system like EMS.   This page https://stason.org/TULARC/pc/motherboards/Z/ZENITH-DATA-SYSTEMS-8088-Z-159.html seems to reference EMS.

MartyPC 0.3.0 will emulate the Lo-Tech EMS card which can provide 2MB of additional EMS memory, for a generic PC or compatible.  If the Z-159 had onboard-EMS support that would need to be explicitly added.  I can't say emulation of the Zenith systems have been on my radar, but I wouldn't reject a PR to add them.

**Comment by starcrescent** [comment]
I am sorry for the title. It was my first request.
I have not owned any of those machines. They are just examples.
You are right about EMS circuitry in Z-159 but Z-148 aka "College PC" was very cheap (if not the cheapest) and did not include such circuitry.
Here: https://www.1000bit.it/js/web/viewer.html?file=%2Fad%2Fbro%2Fzenith%2Fz148%2Epdf it says RAM (768K non-compatible mode) however there is no information about video modes except "RGB output"
Here https://www.youtube.com/watch?v=H02Jo7D15MQ you can see, you just plug 9x256K chips to motherboard to arrive 768KB RAM.

**Comment by dbalsom** [comment]
Some of the Tandy 1000 line could have 768KB of ram installed, but the last 128k would be used by the video system. 

I guess to answer your question, there's no problem implementing however much memory you want in any system. You can give an XT 1MB of conventional memory if you want, but hardware devices and ROM areas will overwrite it, leaving you with gaps.  If I ever implement the Zenith line we can be sure to support the correct amount of RAM.

**Comment by starcrescent** [comment]
> You can give an XT 1MB of conventional memory if you want
How could I do that?

**Comment by starcrescent** [comment]
> You can give an XT 1MB of conventional memory if you want

How could I do that?

**Comment by starcrescent** [comment]
> You can give an XT 1MB of conventional memory if you want

How could I do that? None of the memory of the models go over 640KB

**Comment by dbalsom** [comment]
> How could I do that? None of the memory of the models go over 640KB

You can change the amount of conventional memory in a machine configuration.

So for example if I want an XT with 736K of memory, I would edit ibm5160.toml:

change this line:
```
    [machine.memory]
    conventional.size = 0xA0000
```

to this:
```
    [machine.memory]
    conventional.size = 0xB8000
```

You will need to use GLaBIOS to see the full 736K.

**Comment by starcrescent** [comment]
Thank you.

**Comment by starcrescent** [comment]
Did not work! 86Box overwrites config file to correct memory size to 640KB'

**Comment by dbalsom** [comment]
86box?   Sorry I'm confused. If you mean MartyPC, it actually can't write to configuration files so I am not sure how it would be overwritten...

**Comment by OBattler** [comment]
Perhaps it's time to transfer the issue to the 86Box repository?

**Comment by OBattler** [comment]
Well, if the issue is with 86Box - it's NOTABUG - you need to add a memory expansion card starting at 640 kB.

**Comment by dbalsom** [comment]
closing due to lack of response. if you are using MartyPC and still need help with this, you can still reply.
