### ISSUE TITLE
CPU halt on enabling turbo button on startup

### ISSUE THREAD

**Issue by xcloudplatform** [dbalsom/martypc#14]
warpspeed set to true

<img width="657" alt="Screenshot 2023-06-26 at 9 11 53 PM" src="https://github.com/dbalsom/martypc/assets/135233930/b455ec11-877e-4f93-8e9e-321d42cafcf0">

tried to click on and off on the turbo button in gui, run/start CPU

**Comment by dbalsom** [comment]
was this built from the 0.1.2 branch?

**Comment by dbalsom** [comment]
Please let me know what machine type and ROM you are using, and try to reproduce with warpseed=false.

warpspeed is really a debugging feature for my own use, it is not very stable, and I should probably make a note that I can't accept issues on it with it enabled.

**Comment by xcloudplatform** [comment]
from main

**Comment by dbalsom** [comment]
Ok, I was able to repro finally. This is a rare timing issue with the PIT.  The BIOS continually reads the PIT as its counting and OR's the timer value in a loop to check that all the bits change.  Playing around with the turbo could cause the BIOS to sample the PIT timer twice as fast and complete the loop in half the time, which causes a chance that it doesn't see every bit turn on (the result must be FF after the polling loop)

Considering that the IBM PC and XT didn't have a turbo button, my advice is probably going to be that the results of the turbo button on the PC/XT are not guaranteed.  I would probably wait until the system has booted before enabling it.

**Comment by xcloudplatform** [comment]
Standard Template Construct has invited you to join Slack

[Profile picture of support.][Profile picture of devbox65host.][Profile picture of support.][Profile picture of JetBrains Sales Americas.][Profile picture of info.][Profile picture of contact.]

Join the conversation with Standard Template Construct in a workspace called custom-gpts.

Join Slack [https://join.slack.com/t/custom-gpts/invite/enQtNzY5MzQxODYxNzc3OC0xNjk2YzA1YWNjZmUxYTIxYmM2NDg5MGQxNTZjMTA1YTU3MDY5MWMwMDkwYzdiMWQ2M2IzZGRjNDUzOTQ4MzAy?x=x-p7690535638485-7678860986599-7706089383825]

Once you join, you can always access your team’s workspace, custom-gpts, at https://custom-gpts.slack.com/

What is Slack?

Slack is a messaging app for teams, a place you can collaborate on projects and organize conversations — so you can work together, no matter where you are.

Learn more [https://slack.com/help/articles/115004071768-What-is-Slack-]

**Comment by xcloudplatform** [comment]
Accept Standard Template Construct’s invitation to Slack

[Profile picture of info.][Profile picture of support.][Profile picture of devbox65host.][Profile picture of support.][Profile picture of Raf from OpenAI.][Profile picture of repo-discuss.]

Join the conversation with Standard Template Construct in a workspace called custom-gpts.

Join Slack [https://join.slack.com/t/custom-gpts/invite/enQtNzY5MzQxODYxNzc3OC0xNjk2YzA1YWNjZmUxYTIxYmM2NDg5MGQxNTZjMTA1YTU3MDY5MWMwMDkwYzdiMWQ2M2IzZGRjNDUzOTQ4MzAy?x=x-p7690535638485-7678860986599-7713155259729]

Once you join, you can always access your team’s workspace, custom-gpts, at https://custom-gpts.slack.com/

What is Slack?

Slack is a messaging app for teams, a place you can collaborate on projects and organize conversations — so you can work together, no matter where you are.

Learn more [https://slack.com/help/articles/115004071768-What-is-Slack-]
