### ISSUE TITLE
Compiled release ?

### ISSUE THREAD

**Issue by ArnoldUK** [dbalsom/martypc#3]
Hi, do you have a compiled binary for Windows ? I don't use rust and cannot compile the sorce code.
Thanks.

**Comment by qeeg** [comment]
Dude, it's super easy, just download rustup, install it, then open a new command prompt, and go to the directory the marty code is in, then type `cargo run --release` and hit enter. Not hard.

**Comment by ArnoldUK** [comment]
Ok, I will give it a go. THought I had to download and setup VS code which I dont like using.
Thanks for advice..

**Comment by qeeg** [comment]
I mean, you might have to install Visual Studio 2022 to get it to work, but... What's the issue with VS Code? It's a great text editor lol.

**Comment by ArnoldUK** [comment]
I dont have the time to install and setup visual studio or vscode, I've tried it before, nothing worked and I'm now commited to not try it again. I wasted hours downloading gigabytes of files and updates.

If it was as simple as you said to download a single file and run a single command then yes, I'm all for that.
 Thanks anyway.

**Comment by dbalsom** [comment]
Hi Arnold,

I don't have a release yet as this has been under heavy development and lacking what I'd consider to be important user facing features like basic emulator controls, documentation and protections against corrupting your VHD.  I'd say a release is likely soon, I'm working on supporting Area5150 and when that is complete I am going to take a polish pass and make an initial release.  Might be a week or two. Thanks for your interest!

**Comment by ArnoldUK** [comment]
Ok, I keep a watch on it.

**Comment by dbalsom** [comment]
Good news, Area5150 is working. Plan to make a release this weekend.

**Comment by dbalsom** [comment]
Apologies for not getting a release out - things needed a bit more polish than anticipated.

**Comment by ArnoldUK** [comment]
Sure, thats cool, not bothered about bugs, only wanted to see what it can do.

**Comment by shakeyourbunny** [comment]
Does this emulator also work with Linux?

Perhaps you would consider - if you are making releases - AppImages?

**Comment by dbalsom** [comment]
I've successfully compiled it on Ubuntu, Windows, and an M1 MacBook Air. 

I'll look into AppImages.  Initial releases will probably just be for Windows until I can get a handle on the build process.

**Comment by ArnoldUK** [comment]
looks well polished, can't wait to give it a go. I will look out for the windows binary. Thanks.

**Comment by dbalsom** [comment]
Have fun!
https://github.com/dbalsom/martypc/releases/tag/0.1.1

**Comment by ArnoldUK** [comment]
So far i'm very impressed with the debug features but not tested everything to give a full report. Thanks fr the build.
