### ISSUE TITLE
EGL init fails on ubuntu 23.04

### ISSUE THREAD

**Issue by jcupitt** [dbalsom/martypc#35]
Hi! I tried on Ubuntu 23.04 and martypc *almost* starts up. I get a window with some working menus, but the main area stays black.

I get this in the output:

```
john@banana ~/GIT/martypc/install (main) $ ../target/debug/martypc 
[2023-07-04T17:06:11Z ERROR wgpu_hal::gles::egl] EGL 'eglInitialize' code 0x3002: EGL_BAD_ACCESS error: In eglInitialize: EGLDisplay (0x5574896f1cc0): Backend failed to allocate context
    
Couldn't create specified video tracelog file: No such file or directory (os error 2)
[2023-07-04T17:06:11Z ERROR marty_core::machine] Couldn't create specified CPU tracelog file: ./traces/instr_trace.log
Couldn't create specified CPU tracelog file: ./traces/instr_trace.log
```

The `Performance ...` window shows this:

![image](https://github.com/dbalsom/martypc/assets/580843/662880be-a0ba-40dd-8061-454b5b7b60f2)

I don't know if there any any useful clues there.

`Settings / About` shows:

![image](https://github.com/dbalsom/martypc/assets/580843/02c5dd78-351a-40bb-9ab8-b73f270b24c3)

And it's an x11 desktop session.

**Comment by jcupitt** [comment]
In case it's relevant, I built martypc with `cargo build`, I downloaded the 8088 GLABIOS rom, made an `icon.png` (it was complaining about this) in `install/`, and added a rom override to the toml:

```
rom_override = [
    { path = "./roms/GLABIOS_0.2.4_8T.ROM", address = 0xF0000, offset=0, org="Normal" },
]
```

**Comment by dbalsom** [comment]
> In case it's relevant, I built martypc with `cargo build`, I downloaded the 8088 GLABIOS rom, made an `icon.png` (it was complaining about this) in `install/`, and added a rom override to the toml:
> 
> ```
> rom_override = [
>     { path = "./roms/GLABIOS_0.2.4_8T.ROM", address = 0xF0000, offset=0, org="Normal" },
> ]
> ```


That is very relevant - I put the rom_override feature in mainly for rom developers so that they could force the emulator to use a specific rom, otherwise MartyPC is limited to the ROM hashes it knows about in its internal database ( I need to factor this out to an external definition file)

You were really close; you just need to load GLaBIOS at 0xFE000.

**Comment by jcupitt** [comment]
> You were really close; you just need to load GLaBIOS at 0xFE000.

And that did it! Thank you, I'll close.

**Comment by dbalsom** [comment]
Just another note - if you use the rom_override feature (which is fine, it lets you experiment with a bunch of ROMs I don't otherwise 'support') you are responsible for ALL the ROMs. So if you want to add a hard disk controller, you need to add another line and load the Xebec ROM there too, same for EGA and VGA.

**Comment by jcupitt** [comment]
The GLaBIOS download page:

https://github.com/640-KB/GLaBIOS/releases

Seems to suggest `GLABIOS_0.2.4_8T.ROM` (it's the first one they list), but `roms.txt` lists a GLaBIOS with a different checksum:

```
$ md5sum GLABIOS_0.2.4_8T.ROM 
cfcdd125e70d3f2343388c83ffabd6c7  GLABIOS_0.2.4_8T.ROM
```

**Comment by dbalsom** [comment]
The author of GLaBIOS was kind enough to create customized versions of GLaBIOS for MartyPC, those are included in the 0.1.2 binary release. They have special features. 

Since GLaBIOS is under active development, the GLaBIOS ROMS in the release archive are the only roms in my ROM definition database.

**Comment by jcupitt** [comment]
Ah, I understand. I'll do that.

**Comment by dbalsom** [comment]
I notice that from your screenshot your render time is pretty high. at 7.3ms. It should be under 1ms. Would you be willing to install cargo flamegraph and take a measurement for me so I can see where that time is going? 

https://github.com/flamegraph-rs/flamegraph

**Comment by jcupitt** [comment]
I'd expect it to be slow -- it's a cheap GPU running two 1440p screens and a fancy shell. I'll try flamegraph tomorrow.

**Comment by dbalsom** [comment]
The stuff in 'render time' actually runs on your CPU

**Comment by jcupitt** [comment]
I had a go:

```
$ flamegraph -o x.svg -- ../target/debug/martypc
```

Then quit after a second or so.

http://www.rollthepotato.net/~john/x.svg

**Comment by dbalsom** [comment]
Thanks. For some reason the CGA device is taking 7x as much time to run as it should.  Strange.

**Comment by dbalsom** [comment]
just a thought, when you build did you do 'cargo build' or 'cargo build -r'  ? the former makes a debug build, which is very slow

**Comment by jcupitt** [comment]
Ahhhh yes I'm sure that's it. I didn't realize cargo defaulted to a debug build.

**Comment by dbalsom** [comment]
Youre not the first, it's a little frustrating that the default is a debug build. I've added a UI warning when MartyPC is built in debug mode,  now you can't miss it!
![image](https://github.com/dbalsom/martypc/assets/7229541/5ec2d2a0-2070-4db1-b2ef-bf7d19ae3c83)

**Comment by jcupitt** [comment]
Yeah, meson defaults to debug as well, it's caused quite a few libvips issues. I should add a warning like that.
