### ISSUE TITLE
[Suggestion] Allow for smaller window sizes.

### ISSUE THREAD

**Issue by FavoritoHJS** [dbalsom/martypc#36]
On the martypc_pixels_desktop frontend, the minimum screen size is 1280x960, which can be a little large when working on other stuff.

Worse, if scaled, this can be greater than 1080p, making sure the window doesn't fit on the screen!

**Comment by dbalsom** [comment]
DPI scaling strikes again! 

Thanks for the report. I should be able to let you make the window as small as you like.

**Comment by dbalsom** [comment]
- Minimum window size reduced to 640x480.
- Use DPI scaling setting to calculate if window will fit on the current monitor.

https://github.com/dbalsom/martypc/commit/db189779875c9272e6a5fe61c7028ab096fafc55
