### ISSUE TITLE
no 32bit windows release

### ISSUE THREAD

**Issue by MyTDT-Mysoft** [dbalsom/martypc#41]
why even need a 64bit release for an 8086 emulator????

**Comment by dbalsom** [comment]
if your system is so old that you are running a 32 bit operating system I am afraid that MartyPC would not run well in any case.

64 bit builds can use more RAM but can also be more performant, I use 64 bit writes to draw two pixels at a time (RGBA+RGBA) in my CGA code, for one.

**Comment by ArnoldUK** [comment]
> why even need a 64bit release for an 8086 emulator????

Probably only reason is If your OS only allows 64bit apps to run because of windows secure boot or security policy. But yes, 64bit release over a 32bit release is not going to provide any performance boost in a 8mhz emulator that would be noticed in use.

**Comment by dbalsom** [comment]
> > why even need a 64bit release for an 8086 emulator????
> 
> Probably only reason is If your OS only allows 64bit apps to run because of windows secure boot or security policy. But yes, 64bit release over a 32bit release is not going to provide any performance boost in a 8mhz emulator that would be noticed in use.

The CGA device (at 14Mhz) creates an intermediate representation of the screen at 4bpp.  A single CGA character glyph is 8 pixels wide.  This means I can draw an entire character row in a single 64 bit write.  Correspondingly, the character glyphs are unpacked from their bitwise representation in ROM to 4bpp and cached as 64 bit integers.  Applying the character cell color attributes (background and foreground color) is done with 64 bit bitwise operations an entire row at a time.

The intermediate representation is converted to 32-bit RGBA for display. There are 16x16=256 possible combinations of two intermediate pixels, so again you can convert to RGBA 64 bits at a time using a 256 element LUT with good cache concurrency.

internal copies of data structures can be faster. memory clear operations such as blanking a framebuffer can be faster.

it's definitely noticeable.

**Comment by ArnoldUK** [comment]
I guess internally, yes effectively much faster processing, but running an 8mhz 8088 emulator on a 2Ghz cpu I would struggle to see any speed differences with a fixed FPS of say 60fps.

**Comment by dbalsom** [comment]
On my particular PC, even with the very granular way I tick every device, and with tons of potential CPU optimizations left to implement, MartyPC runs at around 3ms per frame, so i could in theory run 5 instances on a single core, with 23 cores left to spare. That's a lot of Martys.

You are right someone with a fairly new-ish PC is not going to get any more FPS out of the 64 bit version.   But others are not so lucky. I have one user on an i7-860 from 2009 who is still struggling to hit 60fps on the desktop.  That's a 14-year old CPU, but still a 64-bit CPU, so every bit helps.  

Plus the wasm build is not nearly as performant; there are lots of devices like smartphones that struggle with it, but we still have 64-bit integers in wasm.  Every little bit helps.

I don't want to get on a huge tangent about 32-bit vs 64-bit.  I guess what I am looking for is the rationale to both build and support a separate 32-bit binary.    From what I can see, the OP has a particularly intense desire to stay on a 32-bit OS for unclear reasons and has opened several issues on other emulators for the same complaint.

I'm going to close this discussion, If someone wants to adjust my CGA code and make a 32-bit version under a cfg flag, I will consider a pull request.

**Comment by ArnoldUK** [comment]
Yes, totally agree with you, I'm running your 32bit build and runs perfect on my core i5 1.8Ghz cpu.
I don't see the point of running an 8088 emulator with more than 30fps anyway as it would nto really be a true emualtor of the 8088 which was not even designed to operate beyond speeds of 12Mhz or even 30fps CGA video.

**Comment by dbalsom** [comment]
The CGA is actually 60fps.

    912 clocks per scanline * 262 scanlines = 238,944 clocks per frame.
    14,318,180Hz / 238,944 clocks equals a 59.92Hz refresh rate.

**Comment by qeeg** [comment]
@ArnoldUK The IBM PC 5150 and PC/XT 5160 were both 4.77 MHz, not 8 MHz.

**Comment by ArnoldUK** [comment]
> @ArnoldUK The IBM PC 5150 and PC/XT 5160 were both 4.77 MHz, not 8 MHz.

V20 8088 XT clones ran at 12Mhz and the crystal limited the speed.

**Comment by shakeyourbunny** [comment]
> why even need a 64bit release for an 8086 emulator????

If you are not aware, in reality Windows 32-Bit applications run in 64-Bit Windows already under emulation. Also Windows has to provide all the support DLLs also in a 32-Bit version. For technical details, see https://learn.microsoft.com/en-us/windows/win32/winprog64/wow64-implementation-details .

There may be very be a future Windows which ditches all 32-Bit compatibility, as 64-Bit Windows already did with 16-Bit Windows applications.

On Linux, if you want to run 32-Bit applications, you also have to provide all libraries which the application uses in a 32-bit version. There are already distributions which ditched 32-Bit completely.

**Comment by ArnoldUK** [comment]
> The CGA is actually 60fps.
> 
> ```
> 912 clocks per scanline * 262 scanlines = 238,944 clocks per frame.
> 14,318,180Hz / 238,944 clocks equals a 59.92Hz refresh rate.
> ```

Thats correct but was there ever an XT clone that could put out 60fps of graphics or video.

**Comment by qeeg** [comment]
Yes? That's what @dbalsom JUST said.

**Comment by shakeyourbunny** [comment]
> > @ArnoldUK The IBM PC 5150 and PC/XT 5160 were both 4.77 MHz, not 8 MHz.
> 
> V20 8088 XT clones ran at 12Mhz and the crystal limited the speed.

This emulator is about the IBM5150 and not XT clones.

**Comment by shakeyourbunny** [comment]
> > The CGA is actually 60fps.
> > ```
> > 912 clocks per scanline * 262 scanlines = 238,944 clocks per frame.
> > 14,318,180Hz / 238,944 clocks equals a 59.92Hz refresh rate.
> > ```
> 
> Thats correct but was there ever an XT clone that could put out 60fps of graphics or video.

https://www.youtube.com/watch?v=BdM5j96tEpE

**Comment by dbalsom** [comment]
> > The CGA is actually 60fps.
> > ```
> > 912 clocks per scanline * 262 scanlines = 238,944 clocks per frame.
> > 14,318,180Hz / 238,944 clocks equals a 59.92Hz refresh rate.
> > ```
> 
> Thats correct but was there ever an XT clone that could put out 60fps of graphics or video.

Both 8088MPH and Area 5150 have 60fps effects on an original IBM 5150.

**Comment by ArnoldUK** [comment]
> > why even need a 64bit release for an 8086 emulator????
> 
> If you are not aware, in reality Windows 32-Bit applications run in 64-Bit Windows already under emulation. Also Windows has to provide all the support DLLs also in a 32-Bit version. For technical details, see https://learn.microsoft.com/en-us/windows/win32/winprog64/wow64-implementation-details .
> 
> There may be very be a future Windows which ditches all 32-Bit compatibility, as 64-Bit Windows already did with 16-Bit Windows applications.
> 
> On Linux, if you want to run 32-Bit applications, you also have to provide all libraries which the application uses in a 32-bit version. There are already distributions which ditched 32-Bit completely.

I'm talking about locked down systems that won't allow any 32bit apps to run. Sure, they can run as 64bit emulated processes, that's nothing new like you said.

**Comment by ArnoldUK** [comment]
> > > The CGA is actually 60fps.
> > > ```
> > > 912 clocks per scanline * 262 scanlines = 238,944 clocks per frame.
> > > 14,318,180Hz / 238,944 clocks equals a 59.92Hz refresh rate.
> > > ```
> > 
> > 
> > Thats correct but was there ever an XT clone that could put out 60fps of graphics or video.
> 
> Both 8088MPH and Area 5150 have 60fps effects on an original IBM 5150.

Sorry, I'm not talking about tweaked demos, I'm talking about general dos apps, games and windows.

**Comment by qeeg** [comment]
@ArnoldUK They still ran on the same hardware, so try again lol.

**Comment by dbalsom** [comment]
Ok, this discussion has run its course.
