### ISSUE TITLE
infocom display

### ISSUE THREAD

**Issue by Sanesecurity** [dbalsom/martypc#46]
![moonmist-1](https://github.com/dbalsom/martypc/assets/15154470/ff9ffca7-569a-4e32-8b45-5602dde1f59a)
![moonmist](https://github.com/dbalsom/martypc/assets/15154470/88915e34-11eb-4b0e-a2a9-46514b022b27)

Moonmist and I assume other infocom adventures don't display correctly, ie. no title bar with time on it at the top.

booted using freedos.

Not sure if this is a martypc issue or freedos etc.

**Comment by dbalsom** [comment]
Not a bug.

![image](https://github.com/dbalsom/martypc/assets/7229541/26002484-d81e-485c-a21f-b576d7bb6d30)

Moonmist and other infocom titles require either ANSI.SYS or NANSI.SYS loaded in your config.sys. 
The Moonmist installer should have done this for you, if you installed it to your hard drive.

If you're running from floppies, I made a boot floppy for you:
[ansi_boot.zip](https://github.com/dbalsom/martypc/files/12001674/ansi_boot.zip)

It might be worth modifying the Freedos image i ship with MartyPC so this is loaded automatically.

**Comment by Sanesecurity** [comment]
Ah, my fault. Thanks for the hint!

**Comment by dbalsom** [comment]
No problem, added this in a FAQ section of the wiki.
