### ISSUE TITLE
Multitasking DOS 4.0 (Internal revision 6.7 85/11/26) hangs during boot

### ISSUE THREAD

**Issue by starfrost013** [dbalsom/martypc#56]
**Describe the bug**
Multitasking MS-DOS 4.0 fails to boot on MartyPC.

The system hangs because it is looping for the memory address at `[DS:0568] (0x05E01)` to be `0xFF`, but in MartyPC it appears to be `0x00`, which means the system loops forever and does not continue to boot. The memory address in question only appears to be set by the BIOS prior to being checked by the kernel. I tested with both the May 9, 1986 IBM XT bios and the default BIOS (GlaBIOS) provided with MartyPC. The relevant code is located at 0x3DE2-3DE8 in the kernel (<code>IBMDOS.COM</code>). Not sure what is causing it - but have verified the kernel and bootloader are being copied into memory correctly. There is some kind of 8087 init code near what is freezing, but the system boots correctly on 86Box with no FPU.

**To Reproduce**
1. [Download this disk image](https://winworldpc.com/download/0b1a65c2-ba46-c2b0-11c3-a4c28d587054)
2. Copy both images to the MartyPC disk image folder
3. Insert the "DISK1" labelled image file into Drive A:
4. Run MartyPC.
5. Wait for the "MS-DOS Version 4.00" text to appear.
6. The system will hang.

**Expected behavior**
The operating system boots to its shell.

**Screenshots**
![image](https://github.com/dbalsom/martypc/assets/12046237/12024d5c-71ca-4c8e-b1a0-0115f37bd553)

**Environment (please complete the following information):**
 - OS Version / Distribution: [e.g. Windows 10, Linux / Ubuntu 23 ]: Windows 11 22H2 (OS Build 22621.1992)
 - CPU model: AMD Ryzen 5 3600
 - GPU model: GeForce GTX 1660 SUPER

**Build info**
Tested with both 0.1.3 and code built from [28c0586](https://github.com/dbalsom/martypc/commit/28c05866a20cba7579041b96282fddcc81505d50), release configuration, on Windows.

**Config**:
[martypc.toml.zip](https://github.com/dbalsom/martypc/files/12207483/martypc.toml.zip)

**Comment by dbalsom** [comment]
This version of DOS sets an unusual interrupt vector offset in ICW2 to the PIC which I wasn't handling.
![image](https://github.com/dbalsom/martypc/assets/7229541/8f699225-6904-46a8-be62-724929ad19e2)

There's still an issue where it doesn't boot if the Xebec controller is configured. 86box doesn't have this issue so that will need further investigation.

**Comment by starfrost013** [comment]
very nice - is it committed yet? doesn't seem to be? I have been working on researching this OS and debugging it so this is really a thanks

**Comment by dbalsom** [comment]
0.1.4 is unstable development, but it is committed here
https://github.com/dbalsom/martypc/tree/ca0441c81f7de646cd6c6c71992072eeb9760f0b

**Comment by lautis0503** [comment]
I try to boot it in both version.
In MartyPC v0.1.3, it hangs.
In MartyPC v0.1.4 https://github.com/dbalsom/martypc/commit/94ce57ce588c698374d67d9a5667f4b4e2d3ad6a, it reports:
`Bad or missing Command Interpreter`

PS: It boots in PCE.

**Comment by starfrost013** [comment]
I think bad or missing conmand interpreter might be a misconfiguration issue if you're booting from floppy (change shell from `a:\command.com` to `c:\command.com`); I booted it from floppy on commit [ca0441c](https://github.com/dbalsom/martypc/tree/ca0441c81f7de646cd6c6c71992072eeb9760f0b)

**Comment by lautis0503** [comment]
> I think bad or missing conmand interpreter might be a misconfiguration issue if you're booting from floppy (change shell from `a:\command.com` to `c:\command.com`); I booted it from floppy on commit [ca0441c](https://github.com/dbalsom/martypc/tree/ca0441c81f7de646cd6c6c71992072eeb9760f0b)

I tried commit https://github.com/dbalsom/martypc/commit/ca0441c81f7de646cd6c6c71992072eeb9760f0b, with the martypc.toml you uploaded, with floppy images downloaded from your link. Everything seems to be the same as yours. But still got a `Bad or missing Command Interpreter`
No idea what happened.

**Comment by dbalsom** [comment]
seems you will get "Bad or missing Command Interpreter" if the Xebec rom is loaded.  I am not sure what the conflict is; I can load the xebec rom in 86box and it will boot.

**Comment by dbalsom** [comment]
My work on Minix has helped here, now we can boot with the xebec controller as well.

![image](https://github.com/dbalsom/martypc/assets/7229541/d5dd3532-5682-4fc7-a114-9b28311e05e8)
