### ISSUE TITLE
3-Demon sprite corruption (Working in 0.1.4)

### ISSUE THREAD

**Issue by jinshin** [dbalsom/martypc#58]
Hi.
Sorry for contacting you via bug report - i coudn't find any other way.
Running 3-Demon in MartyPC 0.1.3 results in garbled sprite graphics.
It's exactly the same problem i'm experiencing running 3-Demon on Book8088.
DOSBox and PCem don't have that problem.
MartyPC 0.1.4 fixes that (built yesterday) and i would be grateful for some clues what exactly might fix the problem.
I've cut out 40h,42h ports out in 3-Demon, thinking that might be incorrect interrupt handling (it installs some stuff on 1Ch) but  the problem is still there. Sprite draw proc located at 2E70h absolute offset (2470h from image start).
Would be really grateful for any hints!
--
Serhii

**Comment by dbalsom** [comment]
Does your Book8088 have a v20 or an 8088 CPU?

**Comment by jinshin** [comment]
It came with V20, but i've checked with Soviet 1989 8088 clone CPU i've extracted from my very old board - same result.

**Comment by dbalsom** [comment]
Does the clone 8088 pass 8088MPH Cpu test? Should see "Thanks for running this on real hardware!"

**Comment by dbalsom** [comment]
I don't want to sound unhelpful but I have so much work to do on issues that haven't been magically fixed by some other bugfix - if you are willing to help, you can use git bisect to find the actual commit from 0.1.4 that fixed it, then we will solve the mystery.

**Comment by jinshin** [comment]
> Does the clone 8088 pass 8088MPH Cpu test? Should see "Thanks for running this on real hardware!"

It says 6% difference, it might be related to Book8088 crystal, but it runs till end, except for one screen, which i believe is broken due to LCD just cannot init the mode (same problem in the end of AREA5150)

(21% for V20)

> I don't want to sound unhelpful but I have so much work to do on issues that haven't been magically fixed by some other bugfix - if you are willing to help, you can use git bisect to find the actual commit from 0.1.4 that fixed it, then we will solve the mystery.

Thanks, will do that.

**Comment by dbalsom** [comment]
> > Does the clone 8088 pass 8088MPH Cpu test? Should see "Thanks for running this on real hardware!"
> 
> It says 6% difference, it might be related to Book8088 crystal, but it runs till end, except for one screen, which i believe is broken due to LCD just cannot init the mode (same problem in the end of AREA5150)
> 
> (21% for V20)
> 
> > I don't want to sound unhelpful but I have so much work to do on issues that haven't been magically fixed by some other bugfix - if you are willing to help, you can use git bisect to find the actual commit from 0.1.4 that fixed it, then we will solve the mystery.
> 
> Thanks, will do that.

I am guessing that the Book8088 has SRAM, and so its BIOS does not initialize DRAM refresh DMA, which may account for the discrepancy. You could enable it with a utility after boot.  It would be harmless to run against SRAM, it would just occupy the same percentage of CPU time as IBM PC.

**Comment by dbalsom** [comment]
It's possible that the book8088 doesn't have the timer channel #1 output routed to the PIC, so DMA can't ever happen, even if everything is programmed.

Let me know what you find with the bisect!

**Comment by jinshin** [comment]
> Let me know what you find with the bisect!

This commit fixes 3-Demon

commit e8f6b0735646bc2555bed6be76cda5f13cf51375
Date:   Mon Aug 14 15:46:42 2023 -0400

    New BiuState logic

 core/src/cpu_808x/biu.rs   | 430 +++++++++++++++++++++++++--------------------
 core/src/cpu_808x/cycle.rs | 299 ++++++++++++++++---------------
 core/src/cpu_808x/jump.rs  |   3 +-
 core/src/cpu_808x/mod.rs   | 101 +++++++----
 4 files changed, 474 insertions(+), 359 deletions(-)

**Comment by dbalsom** [comment]
Good to know. That was a pretty big refactor, so it's hard to say exactly what part of it was the key...

This was an implementation of my new theory of BIU state logic, which I described in more detail on my blog:
https://martypc.blogspot.com/2023/08/the-8088-prefetch-algorithm.html

There were also some improvements to the DMA scheduler to improve accuracy there as well.

In theory this might make the CPU slightly more accurate in certain edge cases; but it's wild to think a game like 3-Demon would be more picky about this than say, Area 5150. 

let's go through some theories:

 - your Russian 8088 isn't an exact clone of an intel 8088, and maybe MartyPC had some CPU inaccuracy in 0.1.3.  I find this unlikely though, as Dosbox has nowhere near a cycle-accurate 8088 implementation either,  and you said it works there...

 - 3-Demon requires exact DMA emulation, which 0.1.4 improved.  Again, I find this unlikely. I can turn wait states off completely in 0.1.4 and the sprites are still correct


puzzling. maybe I will look more into this if i can find time. It might make an interesting blog article.

**Comment by jinshin** [comment]
Thank you! Just in case - i played 3-Demon on that exact CPU in 1989 :) It's hard to beleive, but i kept main board for some reason all these years and decided to desolder cpu (it was soldered, not socketed) just to test in Book8088.
Thanks again, meanwhile maybe i could find something via debugging

**Comment by dbalsom** [comment]
I tried to find the offsets you mentioned earlier, i had trouble finding the start of a routine there.

here is an IDA disassembly of 3-Demon. Maybe you can help me locate the routine that generate the sprites - I don't think it is the code that draws the sprites, it just looks like a normal copy 

[3-Demon.exe.asm.zip](https://github.com/dbalsom/martypc/files/12411209/3-Demon.exe.asm.zip)

**Comment by jinshin** [comment]
> [3-Demon.exe.asm.zip](https://github.com/dbalsom/martypc/files/12411209/3-Demon.exe.asm.zip)

sub_12470 - if you remove/nop
xor es:[bx+di], al
demon sprites won't be drawn on screen

I don't have IDA, i use hiew32 for quick checks

**Comment by dbalsom** [comment]
that is the drawing routine

```
                mov     ax, 0B800h
                mov     es, ax
                assume es:nothing
                mov     ah, [bp+arg_0]

loc_124A7:                              ; CODE XREF: sub_12470:loc_124C3↓j
                xor     bx, bx

loc_124A9:                              ; CODE XREF: sub_12470+44↓j
                mov     al, ah
                and     al, [si]
                xor     es:[bx+di], al
```

XOR makes sense as it will let the ghosts be drawn and erased with the same operation. the sprite data appears loaded with a parameter passed to this routine [bp+arg_0] and then masked by some value from [si].  I think we have to look at where the sprites are made - if we capture the value of bp+arg_0 in this instance we can then re-run 3-demon with a memory breakpoint there, and maybe see when the sprite data is created

**Comment by jinshin** [comment]
It starts with some magic right from start. It uses negative segment fixup right on init - then copies memory from there to end of available memory. 
I'm gonna learn your built in debugger, using afd pro on Book8088 might take too much time.

**Comment by jinshin** [comment]
Never underestimate the power of old coding :)

Digging the logic, i found that:
Main timer proc is installed on 1Ch (good)
Doesn't call previous handler (bad)
Changes AX and DS, but doesn't save/push them.
So i wrote a little TSR that installs dummy handler on int 1Ch, that saves and restores (after calling previous handler) all registers. If a program sets handler to 1Ch to itself, the TSR installs second one on top.

That fixes 3-Demon. Basically int 1c handler in 3-Demon can corrupt register values in the middle of draw. For some reason it didn't happen on my old PC and draw proc is very fast on modern PC, so probably it simply doesn't get called in the middle of draw proc. OR there's some cli/sti instructions that have no effect on MartyPC 0.1.3 and Book8088. Aaand DOSBox most probably saves/restores registers on int call.

The good thing is MartyPC 0.1.4 is so close to real one it even runs bad code well :)
Bad - i've wasted your time, sorry.

Thanks!

**Comment by jinshin** [comment]
https://github.com/jinshin/Book8088/blob/main/3-Demon_MartyPC.exe

Decided to try one more idea - added a slight delay to drawing cycle (in al,20h) and it made it better! Slight corruption is still there, but now it's playable in 0.1.3.
Hopefully that makes sense to you, because i'm more on the reversing side, deep hardware knowledge is not my perc.

**Comment by jinshin** [comment]
Sorry, one last notice: original XT BIOS did save DS, AX and DX registers, but Kiselev's 8088 BIOS - only DS and AX.
Code from 5160:
```
TIMER_INT	PROC	FAR
	STI				; INTERRUPTS BACK ON
	PUSH	DS
	PUSH	AX
	PUSH	DX			; SAVE MACHINE STATE
	CALL	DDS
	INC	TIMER_LOW		; INCREMENT TIME
	JNZ	T4			; TEST_DAY
	INC	TIMER_HIGH		; INCREMENT HIGH WORD OF TIME
T4:					; TEST_DAY
	CMP	TIMER_HIGH,018H		; TEST FOR COUNT EQUALING 24 HOURS
	JNZ	T5			; DISKETTE_CTL
	CMP	TIMER_LOW,0B0H
	JNZ	T5			; DISKETTE_CTL

;------  TIMER HAS GONE 24 HOURS

	SUB	AX,AX
	MOV	TIMER_HIGH,AX
	MOV	TIMER_LOW,AX
	MOV	TIMER_OFL,1

;------ TEST FOR DISKETTE TIME OUT

T5:					; DISKETTE_CTL
	DEC	MOTOR_COUNT
	JNZ	T6			; RETURN IF COUNT NOT OUT
	AND	MOTOR_STATUS,0F0H	; TURN OFF MOTOR RUNNING BITS
	MOV	AL,0CH
	MOV	DX,03F2H		; FDC CTL PORT
	OUT	DX,AL			; TURN OFF THE MOTOR
T6:					; TIMER_RET
	INT	1CH			; TRANSFER CONTROL TO A USER ROUTINE
	MOV	AL,EOI
	OUT	020H,AL			; END OF INTERRUPT TO 8259
	POP	DX
	POP	AX
	POP	DS			; RESET MACHINE STATE
	IRET				; RETURN FROM INTERRUPT
TIMER_INT	ENDP
```
So, for Book8088 it's more of BIOS bug (or not exact compat)

**Comment by dbalsom** [comment]
Thanks for your help investigating this one!
