### ISSUE TITLE
Jungle Hunt Not Working

### ISSUE THREAD

**Issue by GreatHierophant** [dbalsom/martypc#60]
Jungle Hunt is not working with MartyPC 0.1.3.  You can set options but starting the game just gives you a blank screen. I believe that Jungle Hunt uses the 6845's light pen registers for timing the mid-screen palette change in-game.

**Comment by dbalsom** [comment]
And I was just joking around with 640KB about how nothing uses the light pen registers...

**Comment by dbalsom** [comment]
implemented the light pen latch and registers.
![image](https://github.com/dbalsom/martypc/assets/7229541/5368091d-71da-4e77-a84e-522fdbaa2d5c)

**Comment by dbalsom** [comment]
I suppose this was intended for composite displays?

![image](https://github.com/dbalsom/martypc/assets/7229541/67018b19-cfba-4c0f-8415-6db09a315e67)

the palette change position is a bit unstable, but I heard rumors that it was on a real pc too. I'll have to test on the 5150.
