### ISSUE TITLE
MINIX 1.1 hangs during boot

### ISSUE THREAD

**Issue by lautis0503** [dbalsom/martypc#61]
**Describe the bug**
MINIX 1.1 hangs during boot, with one blinking cursor.

**To Reproduce**
1. Create an XT 5160 machine with CGA.
2. Download [MINIX 1.1 floppy disks](https://mirror.math.princeton.edu/pub/oldlinux/Linux.old/Minix/old/1.1/Floppies/)
3. Insert MINIX disk one, and power on the machine.
4. When the prompt displayed, insert MINIX disk two, then press "=" key.

**Expected behavior**
MINIX should boot.

**Screenshots**
![MartyPC](https://github.com/dbalsom/martypc/assets/16025671/4412eb37-4964-4b63-8b99-fbe77896bc06)

**Build info**
MartyPC v0.1.3 from release page of this repo.

**Additional context**
1. ROMs copied from 86Box.
2. These floppy disks are confirmed to run correctly in Hampa's PCE.
3. The Xebec controller doesn't matter, it always hangs.

**Comment by dbalsom** [comment]
going to hazard a guess it is related to https://github.com/dbalsom/martypc/issues/56

**Comment by lautis0503** [comment]
Building the latest v0.1.4 commit https://github.com/dbalsom/martypc/commit/94ce57ce588c698374d67d9a5667f4b4e2d3ad6a
It still hangs. Nothing changed.

**Comment by lautis0503** [comment]
Forgot to say: these floppy disks of MINIX 1.5 also works fine in PCE.

**Comment by dbalsom** [comment]
Finally found some time to sit down and look at this one.  It's an issue with some bad logic in my PIC.

Namely, when a bit in the IMR is cleared and the corresponding bit in the IRR is set, that IR # will fire an interrupt.  That all works fine; the problem is when multiple bits are set in the IRR and unmasked all at once - a situation that occurs during Minix boot when the IMR is suddenly cleared when we have pending timer, floppy and hard drive interrupts due to the IMR previously being fully masked. 

What happens is that the timer interrupt fires off, being the highest priority and all, and so the floppy and hard drive IRR bits never get processed because there's no logic to promote an IRR bit to an interrupt unless it was just set or just unmasked.

Pretty simple bug, it's just odd I didn't run into this situation before.  All I need to do I think is just to add a IRR promotion check to the PIC's run() method, so that we can handle multiple interrupts being unmasked simultaneously.

**Comment by dbalsom** [comment]
Well, with that fixed, we get a little further. Seems its not happy with disk #2.
![image](https://github.com/dbalsom/martypc/assets/7229541/5d12645a-9469-4fb6-bf46-d3a1bafd07b2)

I think this one is a FDC issue. It tries the Fix Drive Data and Calibrate commands a few times and then gives up, it never actually reads any sectors. It must be unhappy with some value I am returning on calibrate.

**Comment by dbalsom** [comment]
Ok, so I needed to set SEEK_END on calibrate.  It's still not happy about something, but we're getting even further:
![image](https://github.com/dbalsom/martypc/assets/7229541/c244cb51-2b9e-4615-8b55-88081ac9fb7f)

**Comment by dbalsom** [comment]
Minix is reading two sectors at a time. I support this, but I'm not calculating the final chs in the results phase for multi-sector reads properly. DOS apparently doesn't care, whereas Minix checks and throws an error.

**Comment by dbalsom** [comment]
Reworked my CHS calculations to account for multisector operations:

![image](https://github.com/dbalsom/martypc/assets/7229541/40612e7f-e12a-4b8e-b404-613bc8c00a75)

**Comment by lautis0503** [comment]
Congrats. I'll try to run MINIX deeply when you pushing the code.
And I still have a bunch of UNIX-like OSes to try after MINIX. They all work fine in PCE.

**Comment by dbalsom** [comment]
I have a lot of respect for PCE, it is a great emulator. But I compare against hardware - if a real IBM can run it, that is motivation enough for me to fix it.

**Comment by lautis0503** [comment]
Yes, those OSes run on IBM PC. They all existed in that era: MINIX, PC/IX, Venix/86, Coherent, Xenix 86.
There are some versions of preconfigurated machines downloadable from PCE website. And I succeded in installing some other versions.

**Comment by dbalsom** [comment]
I haven't had nearly enough time to test everything out there, so I appreciate you testing out MartyPC's limits.

**Comment by dbalsom** [comment]
> Pretty simple bug, it's just odd I didn't run into this situation before. All I need to do I think is just to add a IRR promotion check to the PIC's run() method, so that we can handle multiple interrupts being unmasked simultaneously.

this fix despite seeming to be "obviously correct" has broken boot on several clone XT BIOS.  I might revert it for 0.2.0 until if I cannot figure out why before release.

**Comment by dbalsom** [comment]
I had a recent breakthrough with my PIC emulation, so I thought I'd give Minix 1.5 another go.  First it gets stuck waiting for a serial interrupt - I know my serial ports need work, so I just took them out of the machine configuration, and Minix moved on.

Next, it was getting stuck on HDC reset. Apparently I need to move the HDC to "Waiting for command" state after reset, after some period of time. I have just made that 200ms for lack of precise measurement.

However, it doesn't seem to want to boot further than this:

![image](https://github.com/dbalsom/martypc/assets/7229541/784049c0-4558-44d7-b8bf-7000f933237c)

which floppy am I supposed to have inserted when hitting = ?

**Comment by lautis0503** [comment]
> which floppy am I supposed to have inserted when hitting = ?

@dbalsom If you have twelve 720K floppies

>Minix 1.5 3"1/2 for the IBM PC,
XT, AT, 386 and PS/2

>Disk numbering:
01: PC Boot Disk
02: AT Boot Disk
03: Universal Boot Disk
04: Root File System
05: System Binaries 1 (/usr)
06: System Binaries 2
07: System Binaries 3
08: Operating System Sources
09: Command Sources 1
10: Command Sources 2
11: Networking Sources
12: Boot Disk with ST 506 Hard Disk

After the prompts show up:
1. Eject boot disk and insert disk04 _Root File System_.
2. Press **r**, select root device.
3. Input **f0**, choose floppy drive 0 (first floppy drive).
4. Press **ENTER** key, confirm root device.
5. Press **=** key, boot.

MINIX reports memory size, real mode, and prompts for /usr diskette.
Then insert disk05 _System Binaries 1 (/usr)_, press **ENTER** key to confirm.

I cannot boot in MINIX 1.5 using PCE now. But I remember the steps.

**Comment by dbalsom** [comment]
![image](https://github.com/dbalsom/martypc/assets/7229541/0e6e63ec-ec98-467e-b3df-2dd95eb813e6)

I fixed the serial issues - I wasn't clearing the transmission buffer interrupt properly.

Next up I needed to implement the Read Sector ID command on the FDC; nothing prior to this had ever called it so I hadn't bothered.

Minix 1.5 boots now; but I have no idea what I'm doing... :)

**Comment by lautis0503** [comment]
> Minix 1.5 boots now; but I have no idea what I'm doing... :)

The next step would be writing C codes. But it takes time to learn how to use the editor. The compiler in MINIX, ACK, is just an old-fashioned K&R C compiler, nothing special to code.

**Comment by lautis0503** [comment]
Latest commit, MINIX 1.5. Similar to what you had before.
![screenshot002](https://github.com/dbalsom/martypc/assets/16025671/2a50bfa6-0c57-414e-9e74-b30c06effb4b)

**Comment by dbalsom** [comment]
![image](https://github.com/dbalsom/martypc/assets/7229541/1695999c-f451-4b49-aa9c-84891f05dfb5)

if you have write_protect_default = true you'll need to reset the write protect option every time you change disks. this is a bit annoying so that option will probably default to false.

there seems to be a little bug that if you try to remove the write protect flag after it's already thrown a write protect error, it doesn't seem to work

**Comment by lautis0503** [comment]
`write_protect_default = false` and it works.

**Comment by dbalsom** [comment]
Let me know if there are any other issues.
