### ISSUE TITLE
Please add build and run instructions to the doc :)

### ISSUE THREAD

**Issue by rationalism** [dbalsom/martypc#70]
Hi! The docs don't seem to include the build and run instructions:

`cargo build --release`
`cargo run --release`

I'm familiar enough with software that I figured it out, but would be helpful for anyone who doesn't already know Rust. Thank you :)

**Comment by dbalsom** [comment]
There's a bit more to it as well as you may need to install dependencies on different platforms. 

Just fyi, cargo run will also build the project first.

**Comment by dbalsom** [comment]
I've started a Wiki page with build instructions. I'll flesh this out a bit more. I can't remember all the dependencies I had to install on Ubuntu but I'll reinstall a fresh VM and document everything I had to do. If anyone wants to contribute instructions for other repos that would be helpful.

https://github.com/dbalsom/martypc/wiki/Building-MartyPC
