### ISSUE TITLE
Disk images with .MNX extension are not visible in menu

### ISSUE THREAD

**Issue by rationalism** [dbalsom/martypc#72]
Hey, I'm trying to use the emulator to run Minix 2.0.2, which is the last version supported on 8088 PCs. The disk images are available here:

https://www.minix-vmd.org/pub/minix/2.0.2/

however, they were silently not visible in the emulator menu under "Media" -> "Load floppy in Drive A". Renaming the .MNX files to .IMG worked, but that was just a lucky guess on my part. Thank you

**Comment by dbalsom** [comment]
Raw sector images are ..raw. They have no header, footer, tag or metadata, and thus the only way to tell something is a floppy image is by the extension, or the exact file size. 

'MNX' doesn't sound like a standard extension used for floppy images, but a specific extension someone picked to be cute. (I could be wrong!) 

I could just allow you to load any file that appeared in your floppy directory, but inadvertently loading a text file or a JPEG into your floppy drive was somthing i wanted to avoid. Also I didn't want to show other floppy types like TD0 and IMD that I do not support, which would just lead to confusion if I allowed them to be loaded.

I suppose it would be fairly safe to show files that either have the correct extension, OR are exactly the right size to be a known raw sector image.

**Comment by dbalsom** [comment]
Based on your comment from the other issue, your MNX disk images are "short" and thus there's really no way at all to tell it is a floppy image, other than to just know that it is. Wunderbar.

I'm just going to put a list of file extensions to interpret as raw sector images in the config, and people can add whatever they want or whatever else comes along. A short image can be allowed to load, assuming it is some multiple of 512 bytes, and assuming all the sectors are in standard order. The rest of the disk will be all 0's.

**Comment by dbalsom** [comment]
There is now a config section where you can specify what extensions should be considered to be raw sector images:

```toml
[emulator.media]
# Provide a list of file extensions toi interpret as raw floppy sector images.
raw_sector_image_extensions = [ "img", "ima", "dsk", "mnx" ]
```
![image](https://github.com/dbalsom/martypc/assets/7229541/8dfa9818-4bc6-4134-9de1-63b887f08eca)

They may still need to be padded to the correct size first.
