### ISSUE TITLE
Cannot find icon.png error on startup

### ISSUE THREAD

**Issue by rationalism** [dbalsom/martypc#74]
When trying to start the emulator using `cargo run` on the main branch (commit `23617a7500192f35a13ffd65539ef1171581a691`), there's an error that it can't find the file `icon.png`. Moving `icon.png` from the `install/` directory into the repo root directory fixes the issue.

**Comment by dbalsom** [comment]
The intent is to run 'cargo run' from the install directory.
MartyPC needs several files (including the config) and i didn't want to clutter up the root of the repo.

**Comment by dbalsom** [comment]
Going to close as this is covered in https://github.com/dbalsom/martypc/issues/70

**Comment by rationalism** [comment]
@dbalsom I ran `cargo run` from a fresh pull of the repo (on `main`) and saw the same error

**Comment by dbalsom** [comment]
> @dbalsom I ran `cargo run` from a fresh pull of the repo (on `main`) and saw the same error

cargo's job is to build an executable, and as long as 'cargo build' produces an executable, then everything is fine as far as I am concerned. I don't intend to recommend use of 'cargo run' as any official way to run MartyPC. 

Your best bet is to run cargo build, then copy the martypc executable out of the target/release directory once built and copy it over the executable from the last official release, which should (hopefully) have a compatible config and directory tree.

Not finding the icon shouldn't be a critical error though, and I plan to address that.  it's a bit of a kludge that I can't use the icon resource in the executable itself to set the window icon using winit, but that's another story.

Your point about needing better (or any) build documentation is valid, I will try to work on build instructions in a future readme update.
