### ISSUE TITLE
Failed to install ELKS due to error in mkfat

### ISSUE THREAD

**Issue by rationalism** [dbalsom/martypc#77]
Tried to install ELKS v0.7.0 (https://github.com/ghaerr/elks/releases/tag/v0.7.0) using martypc (on the branch `version_0_2_0`) to the virtual IBM hard drive, using this installation guide:

https://github.com/ghaerr/elks/wiki#Installation

Here is the link to the relevant floppy disk image:

https://github.com/ghaerr/elks/releases/download/v0.7.0/fd360-fat.img

and here is the Xebec ROM that I used:

https://github.com/86Box/roms/blob/master/hdd/st506/ibm_xebec_62x0822_1985.bin

Booting the floppy, and creating the partition table on the virtual drive, worked OK. However, trying to make an FAT file system on the drive (within the ELKS environment booted from floppy) failed, with this error:

```
# mkfat /dev/hda1 41803
Creating FAT16, Cluster size 4
bioshd: bad partition start=0 sect=-1 nr_sects=0
bioshd: I/O error: dev 301, block 0
Can't create FAT image on /dev/hda1
```

`fdisk /dev/hda` displays this partition information:

```
Geometry: 614 cylinders, 4 heads, 17 sectors
Device #:ID Cyl Head Sect Cyl Head Sect Start Size
/dev/hda1 *1:06 0 1 1 614 3 17 17 41803
```

@dbalsom

**Comment by dbalsom** [comment]
please try it with this env set
RUST_LOG=debug,naga=error,wgpu_core=error,marty_core::devices::hdc=trace

**Comment by rationalism** [comment]
@dbalsom Already fixed! Thank you very much

**Comment by dbalsom** [comment]
i didn't think i changed anything related to hard drives, but ok!

**Comment by dbalsom** [comment]
Can this be closed then?

**Comment by rationalism** [comment]
@dbalsom Yes

**Comment by dbalsom** [comment]
Thanks for testing!
