### ISSUE TITLE
Debug IO Port (0xE9)

### ISSUE THREAD

**Issue by Azhagen** [dbalsom/martypc#79]
QEMU and Bochs have the port 0xE9 available for easy debugging.
Would it be possible to add that port to the emulator?

Azhagen

**Comment by qeeg** [comment]
QEMU and Bochs also only emulate 386 or later CPUs and the main use case for QEMU is as a virtualizer anyway. MartyPC only emulates 8088-based systems currently, and also has far better debugging tools available to you anyway, than just the printf-style debugging that port 0xE9 gives you. You would know this, if you had actually used MartyPC before making this GitHub issue.

**Comment by Azhagen** [comment]
It is sometime simpler to use a printf style debugging, you know.
And yes, I know that there are more powerful tools available, thank you :)

**Comment by dbalsom** [comment]
If I'm reading right output to E9 was just printed to the console? 
I figure you should be able to log any IO port, E9 or otherwise. Would be a good feature to help me debug future device implementations.

**Comment by Azhagen** [comment]
That's right, it simply prints to the console. It also does not need any setup, which is great.

**Comment by dbalsom** [comment]
> That's right, it simply prints to the console. It also does not need any setup, which is great.

do you have an example program that uses it I could test with? do I want to filter output to ASCII printable characters, tab and newline, etc, to avoid garbage / beeps in the terminal?

I can get this in as a quick hack, but in the future I will probably implement it as a "null" device you would install in a machine configuration, with a port and tracelog setting. Tracelogs can already use stdout as an output target.   This way you could have this facility for any port #.

**Comment by Azhagen** [comment]
> do you have an example program that uses it I could test with?

I can make you an example program if you want. I don't have one at hands.

> do I want to filter output to ASCII printable characters, tab and newline, etc, to avoid garbage / beeps in the terminal?

QEMU does not filter the output. It allows any character to be printed.

**Comment by dbalsom** [comment]
I was planning to implement this feature recently, but I stumbled across some interesting concerns

https://www.cyberark.com/resources/threat-research-blog/dont-trust-this-title-abusing-terminal-emulators-with-ansi-escape-characters

Now, the chances of a bad actor making a DOS COM program that attacks your terminal may sound ridiculous, but I would rather MartyPC not have any CVE's assigned to it.

**Comment by dbalsom** [comment]
I've implemented a `terminal_port` field under `[machine]` in the main configuration file. You can set this to any value you like.

![image](https://github.com/dbalsom/martypc/assets/7229541/ddb62224-b150-4cd9-9514-c1d3d2a453af)

the ESC character (0x1B) is filtered to avoid terminal vulnerabilities. If this is an unacceptable limitation, like you really want to emit ANSI graphics or something, we could potentially add an `unsafe_terminal` flag.

**Comment by dbalsom** [comment]
Implemented in [0.2.2 ](https://github.com/dbalsom/martypc/releases/tag/0.2.2)
