### ISSUE TITLE
command line tool to create VHD from a directory 

### ISSUE THREAD

**Issue by darvin** [dbalsom/martypc#8]

**Comment by dbalsom** [comment]
On windows at least, you can mount the VHD created in MartyPC and copy files into it. You would need to google how to mount a VHD on linux or Mac .

I would like to eventually have some feature to mount folders from the host into the emulated system, whether that will be driver-based or a virtual FAT I am not sure.

**Comment by darvin** [comment]
it would be nice to add that to the `README.md`

**Comment by dbalsom** [comment]
I have created a [user guide](https://github.com/dbalsom/martypc/wiki/MartyPC-User-Guide) that mentions this. Closing for now, thank you.
