### ISSUE TITLE
Microsoft Smartscreen / Windows Defender flagging MartyPC as malware

### ISSUE THREAD

**Issue by dbalsom** [dbalsom/martypc#82]
Just going to get ahead of this one. Latest builds seem to be flagged as WACATAC malware by Windows SmartScreen. 

MartyPC doesn't use Tauri but I think this is a similar issue, as Tauri uses Tao, and Tao was a fork of Winit, which I do use: https://github.com/tauri-apps/tauri/issues/2486

In any case, googling WACATAC leads to many, many reports of false positives. 
I plan to bite the bullet and purchase a code signing certificate for MartyPC despite the obscene expense, which hopefully will reduce the weighting of these ML-detections.

**Comment by Tape-Worm** [comment]
Just FYI, it may not be enough to just buy the certificate. At my previous job we had to not only buy the cert but also send information to the AV publisher before they would even issue an update to avoid black listing our applications.

**Comment by dbalsom** [comment]
Yeah, it didn't help in this case.

**Comment by dbalsom** [comment]
Microsoft has corrected the false positive, for now.
