### ISSUE TITLE
Continuous beeping, continuous untyped key input, some OSes stop to work.

### ISSUE THREAD

**Issue by lautis0503** [dbalsom/martypc#88]
This **IS** a very strange issue. Everything works fine one or two days ago.
When I tried to boot into OSes (DOS 2 or DOS 3 or MINIX 1.1), after memory test, there are always continuous but not rhythmed beeping. Some version of DOS floppies would boot, some wouldn't. When DOS told me to input date, it would only recognize one key in several seconds. If I didn't press any key, DOS would recognize a "Y" in random seconds. But the beeping could disappear for no reason after data and time input (but not always). As for MINIX, when it prompts for one key to boot or setup, it continuous receive untyped key input, and this makes it always refresh screen and say "Illegal command" (I could only see a new line, but there must be some ghost keys recognized by MINIX).

What I tried to fix this is:
1. Try different machine configurations, with or without hard drive.
2. Try different floppies to boot (including different floppies of DOS 3, hard drive of DOS 3, floppy of DOS 2, floppy of MINIX 1.1).
3. Remove all build files, `cargo build -r` and `cargo run -r` again.

**Comment by lautis0503** [comment]
For DOS, MartyPC showed a notice in hard drive menu.
![Pic](https://github.com/dbalsom/martypc/assets/16025671/51f7bc2f-92f5-484e-9f66-b292cb2be654)

And MINIX (screenshot in MartyPC menu didn't capture the screen correctly in this situation)
![Pic2](https://github.com/dbalsom/martypc/assets/16025671/4e64f590-4ca9-4eba-b999-f4cd1dd046af)

**Comment by lautis0503** [comment]
One more thing:
I copied the install folder with martypc.exe to other hard drives and then started it.
No beeping, but still strange behaviour. This time, I found that DOS receive commands to "Delete this line to the beginning", which means I can only input two keys and ENTER key to run one command, as more keys to input would take longer and are erased by DOS.

**Comment by dbalsom** [comment]
It sounds a lot like the issues keenmaster was having in https://github.com/dbalsom/martypc/issues/81

Odd as it may sound, can you try unplugging and replugging your keyboard?

Also when you say that the screeenshot didn't capture the screen correctly, can you show what it did produce? Bear in mind that screens are currently not post-processed, so you will not see any shader effects.

**Comment by lautis0503** [comment]
> Also when you say that the screeenshot didn't capture the screen correctly, can you show what it did produce?
What MartyPC captured is, a blank screen with only one underline at the left bottom, looks like a blinking cursor there.

**Comment by lautis0503** [comment]
> It sounds a lot like the issues keenmaster was having in https://github.com/dbalsom/martypc/issues/81

You're right. It's the same. I only checked what he said at the beginning. Now I found what he said later is just as same as mine.

> Odd as it may sound, can you try unplugging and replugging your keyboard?

Everything works now. The point is, I had checked that everything in my host OS works fine, so I thought there was nothing wrong with my keyboard. So weird.

**Comment by dbalsom** [comment]
I suspect it might be an upstream bug in winit library, because I rely on that to get input events from the operating system. I'll have to look at their issues and change notes to see if anything similar has been reported/fixed.

>What MartyPC captured is, a blank screen with only one underline at the left bottom, looks like a blinking cursor there.

did you have the machine paused at that point?

**Comment by lautis0503** [comment]
> did you have the machine paused at that point?

No, the screen was keeping rolling like the picture I uploaded before. (That was captured in host OS)

**Comment by lautis0503** [comment]
One thing not explained. I said that some OSes stop to work. To be specific, it's a hard drive of MS-DOS 3.31 that stopped working.
After memory test, with beeping and blinking cursor, nothing happened. Maybe the DOS was processing too many keys and took longer to boot. I hadn't waited long enough.
