### ISSUE TITLE
how to load msdos & floppy images?

### ISSUE THREAD

**Issue by xcloudplatform** [dbalsom/martypc#9]
better documentation about rom set

**Comment by dbalsom** [comment]
> Found floppy image: "./floppy/000111_another_world.img" size: 1474560
> Found floppy image: "./floppy/001292_battle_chess.img" size: 737280
> Found floppy image: "./floppy/000842_commander_keen_aliens_ate_my_baby_sitter.img" size: 737280
> Found floppy image: "./floppy/000850_commander_keen_marooned_on_mars.img" size: 368640
> Found floppy image: "./floppy/001721_castlevania.img" size: 737280
> Found floppy image: "./floppy/ms_dos_622_disk3.img" size: 1474560
> Found floppy image: "./floppy/ms_dos_622_disk2.img" size: 1474560
> Found floppy image: "./floppy/ms_dos_622_disk1.img" size: 1474560

It supposedly found all these floppies, so they should be selectable under the Media menu. Are they not showing?

**Comment by xcloudplatform** [comment]
https://github.com/dbalsom/martypc/pull/13
