### ISSUE TITLE
Fail to run XEBEC MFM Controller Rom

### ISSUE THREAD

**Issue by Sleora** [dbalsom/martypc#99]
MartyPC seems to don't want to run when I select in the config file `hdc = "Xebec"` and put an appropriate ROM in the right folder. I pulled the ROM from PCem since you don't provide a link for it so I had to guess.
So, dispite all that, MartyPC won't boot unless I change it back to `hdc = "none"`.

**Comment by Sleora** [comment]
That's what bugging me, everything is as it should be and in the right place.  Despite all that MartyPC refuse to boot.

**Comment by dbalsom** [comment]
Please run MartyPC from the command line and share any messages it prints.

**Comment by Sleora** [comment]
What command line ? The Windows Console ?

**Comment by dbalsom** [comment]
> What command line ? The Windows Console ?

yes.

**Comment by Sleora** [comment]
It says `No valid ROM found for requested feature: XebecHDC` dispite having the right ROM in the right place.

**Comment by qeeg** [comment]
@Sleora MartyPC checks for ROMs by hashing them using the MD5 algorithm and checking the hash. What's the MD5 hash of your Xebec ROM? The only one MartyPC accepts is `66631d1a095d8d0d54cc917fbdece684`

**Comment by Sleora** [comment]
How do I check what MD5 hash my file has ?

**Comment by Sleora** [comment]
Ok I checked and it was the same ID as the one you gave: 
![ibm xebec](https://github.com/dbalsom/martypc/assets/47717666/31a5ff84-9368-4408-9882-66afae506534)

**Comment by dbalsom** [comment]
> It says `No valid ROM found for requested feature: XebecHDC` dispite having the right ROM in the right place.

did you change model to "IBM_PC_5150" by chance

**Comment by Sleora** [comment]
Yes? Is it important?

**Comment by dbalsom** [comment]
yeah, 0.1.3 only supports hard disks on XT.  I apologize that the error message is less than helpful in that scenario.

i am going to suggest that you use one of the 0.2 builds - the emulator has pretty much been completely rewritten from 0.1.3, and 0.2 is approaching release candidate. 

if you go the Actions tab, click on the last Workflow run entry that says "Windows" and click the link at the bottom to download the build artifact.  

in 0.2, the roms folder has been moved to /media/roms.  Just put the xebec ROM in there.  the config file has changed quite a bit - now you will want to specify a machine configuration name:

`config_name = "ibm5160_hdd"` will get you an XT with a xebex hdc. try this for now just to make sure it is working.   You can look at the different machine configurations in /configs/machines and change it later.

if that still doesn't work, try running `martypc --romscan` and tell me what it prints.


also I do not recommend putting MartyPC in Program Files.  Program Files is a special directory that requires admin privileges to write to, so you will probably get hard disk errors if your VHD is in there, unless you run MartyPC as admin, which I do not recommend.

**Comment by Sleora** [comment]
Ok, now with the 0.2 version it can boot but I have another problem that arise :
![ibm no screen](https://github.com/dbalsom/martypc/assets/47717666/d933442d-62ef-439e-9d25-32fbd9876243)
I have no image, just plain grey but it does show something if I take a screenshot.

**Comment by dbalsom** [comment]
can you screenshot the performance window under the Emulator menu?

**Comment by Sleora** [comment]
![graph](https://github.com/dbalsom/martypc/assets/47717666/1b2ebaf3-6bb8-4c8c-a0b1-4cddf098192a)

**Comment by dbalsom** [comment]
GeForce GTX 650  - is this correct?   That video card is pretty old, over 10 years old. It may not have proper Vulkan support. 

let's try falling back to DX12.

From a command line type this:
set WGPU_BACKEND=dx12

then run martypc from that commandline.

**Comment by qeeg** [comment]
It was still getting active driver support until 2021, so it SHOULD support Vulkan, if the drivers are up-to-date.

**Comment by Sleora** [comment]
He didn't seems to like it :
![ibm dx12](https://github.com/dbalsom/martypc/assets/47717666/019c6d28-2478-4d67-8efb-501d8a9edfcc)

**Comment by Sleora** [comment]
And yes, it does support Vulkan.

**Comment by dbalsom** [comment]
what is your CPU?

**Comment by dbalsom** [comment]
type 
set RUST_LOG=debug

and try again (in the same window) and show what it prints

**Comment by Sleora** [comment]
Intel i5 2500k

**Comment by Sleora** [comment]
![Uploading ibm dx12.PNG…]()

**Comment by Sleora** [comment]
![ibm dx12](https://github.com/dbalsom/martypc/assets/47717666/ceec37e2-a091-483d-8ac7-514c2c4fe348)

**Comment by dbalsom** [comment]
it can't seem to load dx12.  

we can try opengl as a last resort.

set WGPU_BACKEND=opengl

**Comment by Sleora** [comment]
It works !

**Comment by qeeg** [comment]
You should probably also upgrade to Windows 10 as well. Windows 7 has been out of support except for ESU updates since 2020, and even the ESU updates have been stopped for a year now. It's time to upgrade. Your old system can still handle Windows 10, especially if you use an SSD.

**Comment by dbalsom** [comment]
if you go to your System Properties, Environment Variables, you can can add WGPU_BACKEND=opengl under User variables.   

This will make that setting available to MartyPC outside of the command line and persist on reboot.

**Comment by Sleora** [comment]
Well I would like to but the motherboard I'm using was design for Windows 7 (so it's optimized for it) and right now the drive I'm using is a 7200RPM HDD.
I already tried installing Windows 10 on this machine... twice... I'll not do it again.

**Comment by Sleora** [comment]
Quick last question : is it possible to load a SoundBlaster drive or is it not implemented yet ?

**Comment by dbalsom** [comment]
The only sound device at the moment is the PC speaker, sorry.

**Comment by Sleora** [comment]
Oh... thanks anyway

**Comment by dbalsom** [comment]
At some point I would like to add it, adlib will probably happen first.

If you're all set now I will close this out?
